### PR TITLE
Added Besu information and links in docs:

### PR DESCRIPTION
**Pull request by faraggi**
Some information was incomplete and didn't mention the possibility of using [Besu](besu.hyperledger.org) with web3j. I've added it to the getting started and transactions docs urls.

Signed-off-by: Felipe Faraggi <felipefaraggi@gmail.com>

### CODE REVIEW

**Comment by faraggi** [comment]
Is it normal for these builds to fail? I don't think I made any breaking changes.

**Comment by AlexandrouR** [comment]
The changes are fine. Looks like the build failing comes from `jinja2.exceptions.TemplateNotFound: .icons/.svg` i retriggered a previous build that was passing but i got the same error. I will look into what causes this and update.

**Comment by AlexandrouR** [comment]
The issue was breaking changes in the latest mkdocs-material version I submitted a PR that will fix. The issue should then be fixed.

**Comment by iikirilov** [comment]
@faraggi please rebase this so it can pass the CI

**Pull request merged**
